name: CI/CD dla TypeScript i GitHub Pages

on:
  push:
    branches:
      - main # Zmień na główną gałąź Twojego repozytorium, np. 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Krok 1: Sprawdzenie kodu źródłowego
      - name: Checkout repository
        uses: actions/checkout@v3

      # Krok 2: Ustawienie Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22" # Możesz zmienić wersję Node.js w razie potrzeby

      # Krok 3: Instalacja zależności
      - name: Install dependencies
        run: npm install

      # Krok 4: Kompilacja TypeScript
      - name: Build project
        run: npm run build # Upewnij się, że ta komenda buduje Twój projekt

      - name: Check build output
        run: ls -la

      # Krok 5: Wdrożenie na GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # Ścieżka do folderu z plikami do publikacji
